### ISSUE TITLE
コンテンツの英語化

### ISSUE THREAD

**Issue by mitsut** [toppers/hakoniwa#134]
- 英語ページは `en/` ポリシーで作る
    - [x] やりかたをさがす(@mitsut)

- 英語化の対象ページ
    - [x] TOPの「お知らせ」 `_index.md`
        - 「トピックス・イベント案内」「更新情報」は空で良い．
    - [x] 「箱庭とは」の全部．図は元データを探す． `docs/`
    - [x] 「プロトタイプモデル」 `prototypes/`
        - `single_robot`, `ros2sim` `multiplay` へのランディングページ
        - [x] まず日本語の整理から (@s-hosoai)
    - [x] 「リポジトリ」 repositories.md
    - [x] 「SNS・問合せ先」 contact.md

**Comment by takasehideki** [comment]
リポジトリの README 英語化は，対象の md ファイルを明記しました．
まだ今後に増える可能性はありますが，[余力があれば] のラベルをちゃんと付けて区分けします．

**Comment by takasehideki** [comment]
リポジトリの README 英語化は，それぞれのリポジトリの Issue に移動させました

https://github.com/toppers/hakoniwa-single_robot/issues/16
https://github.com/toppers/hakoniwa-ros2sim/issues/35
https://github.com/toppers/hakoniwa-ros-multiplay/issues/5

**Comment by takasehideki** [comment]
これから各ページの軽いチェックと図の英語化を進めていきます 🚀

**Comment by takasehideki** [comment]
already closed by #143
