### ISSUE TITLE
Getting Started ページの `<title>` が "Getting-starteds" になる

### ISSUE THREAD

**Issue by takasehideki** [toppers/hakoniwa#137]
えいごてきにおかしいw
grep してもソース的に "starteds" は見つからず,,, なぜだろう？？
https://toppers.github.io/hakoniwa/getting-started/

**Comment by takasehideki** [comment]
直りました！あざまっす！！

**Comment by s-hosoai** [comment]
ぎゃ、すみませぬ。。対応ありがとうございます！

**Comment by mitsut** [comment]
いえいえ、多分「箱庭とは」も同様に入っていない状態でtitleが「Docs」で表示されていたので気がつかなかっただけでだと思います。
ただどうして（どうやって）空の場合のデータを引っ張ってきているかは謎ですね。
