### ISSUE TITLE
TOPページに「お知らせ」欄を作る

### ISSUE THREAD

**Issue by takasehideki** [toppers/hakoniwa#14]
ニュース的な表示があるとよい．
さらにそのうちの欲を言えば，「過去のお知らせ」で古いものをまとめておくページもあるとよい．

**Comment by takasehideki** [comment]
ちょっと勘違いしていたかもしれませんが，ニュースごとにmdファイルを作ってやってヘッダで見出しを書いてやって，それをRSS Feedぽく？ブログ記事ぽく？読み込みするのでいいのかもしれないですね．

**Comment by mitsut** [comment]
説明を端折ってましたが、Hugoでは自動的にRSSのindexを作ってくれています。
なので、それをカスタマイズして例えば最新の10エントリを作成するようにして、それをWhatNewとして表示するjsがあればいいのではと考えています。もちろんmdファイルにはdateのエントリーが必要になります。

**Comment by takasehideki** [comment]
了解です．ではその方針で進めることとしましょうか．

**Comment by mitsut** [comment]
参考サイト
https://gammalab.net/blog/bys6b9xbv3jmg/

**Comment by mitsut** [comment]
#65 で解決したのでPRのブランチも削除します。
