### ISSUE TITLE
WGメンバを掲載する

### ISSUE THREAD

**Issue by takasehideki** [toppers/hakoniwa#26]
「問合せ先」ページが良いと思われる

掲載して構わない方に絞って，メンバの氏名・アイコン・GitHubリンク（TwitterやFBも？）を掲載する．

**Comment by takasehideki** [comment]
@mitsut Hugoでなんかできそうという話があったのですが，どうでしたっけ？

**Comment by mitsut** [comment]
> @mitsut Hugoでなんかできそうという話があったのですが，どうでしたっけ？

Themeが違うのですが、このaboutとかの感じですかね。
https://themes.gohugo.io/theme/hugo-elate-theme/

**Comment by takasehideki** [comment]
今からTheme変えるのはけっこう危険が危ない気がしますね．
うまくこの部分だけ持ってくるとか，良い方法があると良いですが，，，

**Comment by mitsut** [comment]
> 今からTheme変えるのはけっこう危険が危ない気がしますね．
> うまくこの部分だけ持ってくるとか，良い方法があると良いですが，，，

この部分だけ持っていくっていう意味でした。テンプレートのhtmlさえなんとかなれば、あとはmdに落とし込めると思うので。
