### ISSUE TITLE
単体ロボット向けシミュレータの導入手順で不足しているインストール手順について

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa#33]
Windows10にWSL ubuntu18を新規に入れて，v850導入手順にそって実施したところ，以下のインストールが必要でした．
①make
②gcc
あと事前に，apt apt-get upateしとかないとgccインストール失敗しますね．

**Comment by takasehideki** [comment]
#39 のPRからリンクすべきIssueを間違えました．これはOpenのままです．

**Comment by ytsuji3333** [comment]
追加で，ETロボコン向けTOPPERS活用セミナーで発表した導入手順の補足情報についても修正する
