### ISSUE TITLE
OGPとTwitterCardを設定する

### ISSUE THREAD

**Issue by takasehideki** [toppers/hakoniwa#45]
ここが参考になりそう
https://exlair.net/hugo-internal-templates-ogp-and-twitter-card/

**Comment by mitsut** [comment]
関連しそうなページ
https://discourse.gohugo.io/t/optimizing-seo-for-blog/19873/17
https://miyahara.hikaru.dev/posts/20200319/

**Comment by mitsut** [comment]
Facebookでのデバッグ表示のページ（[シェアデバッガ](https://developers.facebook.com/tools/debug/)）
Twitterでのデバッグ表示のページ（[Card Validator](https://cards-dev.twitter.com/validator)）

**Comment by mitsut** [comment]
似たようなissueがあった
https://github.com/keitakawamoto/orangebomb.org/issues/117

Kubeのテンプレートではすでに、OGPは対応済みになっている。
kube/layouts/partials/meta/ogimage.html

config.tomlにimagesの情報がないので、フロントマターでアイキャッチの指定がないとなにも出力されないという状況になっている。

とりあえず、hakoniwaロゴを指定するようにする

**Comment by takasehideki** [comment]
すみませんここに貼ったつもりだったんですが，ボケてたようです．
ひとまずOGP向けの画像サイズが小さいみたいですね．
https://github.com/toppers/hakoniwa/pull/54#issuecomment-655841812

**Comment by mitsut** [comment]
Facebookに関する仕様（リンクシェアの画像）
https://developers.facebook.com/docs/sharing/webmasters/images

**Comment by mitsut** [comment]
Twitter Cardに関するドキュメント
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards

**Comment by takasehideki** [comment]
@mitsut  #54 と #57 で対応完了されたことを確認しました．あざまっした！！

**Comment by mitsut** [comment]
Hugoのinternal templateの振る舞いがどのようになっているのか

Hugoのinternal template に関する記述
https://gohugo.io/templates/internal/

Githubのソースコード
https://github.com/gohugoio/hugo/blob/release-0.73.0/tpl/tplimpl/embedded/templates/opengraph.html
https://github.com/gohugoio/hugo/blob/release-0.73.0/tpl/tplimpl/embedded/templates/twitter_cards.html

Internal templateを使った記事
https://exlair.net/hugo-internal-templates-ogp-and-twitter-card/

**Comment by mitsut** [comment]
記事のイメージを使う場合の手順についてはREADME-webに書くことにして本件は閉じます
