### ISSUE TITLE
baseURLと設定パスの関係

### ISSUE THREAD

**Issue by mitsut** [toppers/hakoniwa#7]
baseURLにデプロイ先のURLを記載するとローカルPCでリンクを確認する場合に問題が発生する。
baseURLを空にする("")ことで対応しているが、他に解決策がないか検討する

**Comment by takasehideki** [comment]
`--baseURL` を設定する必要がない？
`static/`配下の画像等のリンクには`/hakoniwa/`が必要？
不思議が多いので，もうすこし様子を見ることにする

**Comment by mitsut** [comment]
@takasehideki 相対パスの設定がありました。
https://gohugo.io/content-management/urls/
https://maku77.github.io/hugo/settings/relativeurls.html
```
relativeurls = true
```
影響範囲が多くて修正漏れが出て来そうなので、コンテンツが落ち着いてから作業します。

**Comment by mitsut** [comment]
@takasehideki やはり調べた結果Hugo のデフォルト動作はbaseURLからの相対パスになります。
'relativeurls = true' にした場合は、リンク情報は現在のページからの相対パスが出力される振る舞いになるため、想定したのと思います。（例えばホームへのリンクなどは崩れる）
やはりこれは使わないほうが良いと思います。

またGithubPagesの出力先は https://toppers.github.io/hakoniwa/となるため、絶対パスとして'/hakoniwa' が必要となります。(逆にいうと'/'であればtoppersの組織サイトのページになる)

コンテンツに'/hakoniwa'が入っているところをみると、ドットインナー変数を使ってい出力しています。これだと相対パスへの変換が行われない（素のhtmlが出力される）のでパス名に '/hakoniwa' が必要になります。

ローカルでデプロイした時に確認する方法を記載する（これはわかりました）とともに、
サイト内では絶対パスでのリンク記述を（なるべく）行わないための記述方法について調査します。

**Comment by mitsut** [comment]
#47 のPRでマージできたのでクローズします

**Comment by takasehideki** [comment]
@mitsut `technical-links.md` のこういうのはOKなんですっけ？

```
- [講演資料 (PDFファイル)
{{< image src="/doc/TOPPERSConf2020-1.png" border="1" width="300" >}}
](/hakoniwa/doc/TOPPERSConf2020-1.pdf)
```
