### ISSUE TITLE
「リポジトリ」ページを作る

### ISSUE THREAD

**Issue by takasehideki** [toppers/hakoniwa#75]
箱庭の活動に関係するソフトウェア・リポジトリの一覧ページを作りたい
表にするか箇条書きで良いかは分量による？

**Comment by takasehideki** [comment]
@mitsut とりあえずメニューバーへの追加と.mdの雛形を作っていただけたらです．
実際のコンテンツは高瀬のほうで整理・作成します．

**Comment by mitsut** [comment]
#77　で対応しました
