### ISSUE TITLE
コンテンツ間のnext, prevリンクの設定

### ISSUE THREAD

**Issue by ytsuji3333** [toppers/hakoniwa#8]
ステップのページに以下のリンク情報があるとうれしい
・次のステップがあるならば、次のリンク
・親もしくは前のステップのリンク

**Comment by mitsut** [comment]
コンテンツのデフォルトのオーダに関する記述
https://gohugo.io/templates/lists/#default-weight--date--linktitle--filepath

**Comment by takasehideki** [comment]
@mitsut これ close しちゃいますかね？？
