### ISSUE TITLE
単体ロボット向けシミュレータの導入手順をRuby 2.7.0に対応する

### ISSUE THREAD

**Issue by ytsuji3333** [toppers/hakoniwa#80]
Ruby 2.7.0が導入されている場合，shellライブラリが標準から外れてしまったため，asp3カーネルのビルドに失敗する．
回避策として，事前に`sudo gem install shell`でshellライブラリをインストールしてもらう旨を導入手順に追記する．

**Comment by takasehideki** [comment]
こちら当該ページがリンクツリーから除外されたと認識しています（ページ自体はまだ存在していそうだけどトップ等からのリンクでは辿れない）．ということでCloseとさせてください！
